# Generated by Django 4.1.3 on 2022-11-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_surfer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfsession',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
