# Generated by Django 4.1.3 on 2022-11-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_surfsession_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfsession',
            name='has_gpx_data',
            field=models.BooleanField(default=False),
        ),
    ]
