# Generated by Django 4.1.3 on 2022-11-10 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_surfer_managers_surfer_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=90, verbose_name='Name')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Longitude')),
            ],
        ),
        migrations.AddField(
            model_name='surfsession',
            name='name',
            field=models.CharField(default='', max_length=90, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='surfsession',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.surfspot'),
        ),
    ]
