# Generated by Django 4.1.3 on 2022-11-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_surfspot_surfsession_name_surfsession_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfspot',
            name='short_name',
            field=models.CharField(default='', max_length=90, verbose_name='Image name'),
        ),
    ]
