# Generated by Django 4.1.3 on 2022-11-10 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_surfspot_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfsession',
            name='duration',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='surfsession',
            name='max_speed',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Speed (km/h)'),
        ),
    ]
