# Generated by Django 4.1.3 on 2022-11-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_surfsession_max_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfsession',
            name='max_speed',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Speed (km/h)'),
        ),
    ]
