# Generated by Django 4.1.3 on 2022-11-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_surfsession_max_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaveConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_speed_to_start_wave', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('min_speed_to_stop_wave', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('minimum_time_of_event_to_consider_wave', models.DecimalField(decimal_places=1, default=2.5, max_digits=4)),
                ('min_max_speed_during_event_to_consider_wave', models.DecimalField(decimal_places=1, default=11, max_digits=4)),
            ],
        ),
    ]
