# Generated by Django 4.1.3 on 2022-11-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_waveconfigs'),
    ]

    operations = [
        migrations.AddField(
            model_name='waveconfigs',
            name='name',
            field=models.CharField(default='', max_length=90, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='waveconfigs',
            name='min_max_speed_during_event_to_consider_wave',
            field=models.DecimalField(decimal_places=1, default=11, max_digits=4, verbose_name='Min. Max speed on wave'),
        ),
        migrations.AlterField(
            model_name='waveconfigs',
            name='min_speed_to_start_wave',
            field=models.DecimalField(decimal_places=1, default=8, max_digits=4, verbose_name='Speed To Trigger Wave Start'),
        ),
        migrations.AlterField(
            model_name='waveconfigs',
            name='min_speed_to_stop_wave',
            field=models.DecimalField(decimal_places=1, default=8, max_digits=4, verbose_name='Speed To Trigger Wave End'),
        ),
        migrations.AlterField(
            model_name='waveconfigs',
            name='minimum_time_of_event_to_consider_wave',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=4, verbose_name='Seconds To Consider Wave'),
        ),
    ]
