# Generated by Django 4.1.3 on 2022-11-14 23:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_waveconfigs_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField(default=datetime.time(0, 0), verbose_name='Duration')),
                ('max_speed', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Speed (km/h)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.surfsession')),
            ],
        ),
        migrations.CreateModel(
            name='WavePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Longitude')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.wave')),
            ],
        ),
    ]
