# Generated by Django 4.1.3 on 2022-11-14 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_wave_wavepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wave',
            name='duration',
            field=models.TimeField(default=datetime.time(0, 0), null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='wave',
            name='max_speed',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, null=True, verbose_name='Speed (km/h)'),
        ),
    ]
