# Generated by Django 4.1.3 on 2023-10-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_wave_duration_alter_wave_max_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfer',
            name='strava_code',
            field=models.CharField(default='', max_length=90),
            preserve_default=False,
        ),
    ]
